#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : fs
Version  : 2.4.11
Release  : 68
URL      : https://github.com/PyFilesystem/pyfilesystem2/archive/v2.4.11/pyfilesystem2-2.4.11.tar.gz
Source0  : https://github.com/PyFilesystem/pyfilesystem2/archive/v2.4.11/pyfilesystem2-2.4.11.tar.gz
Summary  : Python's filesystem abstraction layer
Group    : Development/Tools
License  : MIT
Requires: fs-license = %{version}-%{release}
Requires: fs-python = %{version}-%{release}
Requires: fs-python3 = %{version}-%{release}
Requires: appdirs
BuildRequires : appdirs
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-python

%description
# PyFilesystem2
Python's Filesystem abstraction layer.
[![PyPI version](https://badge.fury.io/py/fs.svg)](https://badge.fury.io/py/fs)
[![PyPI](https://img.shields.io/pypi/pyversions/fs.svg)](https://pypi.org/project/fs/)
[![Downloads](https://pepy.tech/badge/fs/month)](https://pepy.tech/project/fs/month)

%package license
Summary: license components for the fs package.
Group: Default

%description license
license components for the fs package.


%package python
Summary: python components for the fs package.
Group: Default
Requires: fs-python3 = %{version}-%{release}

%description python
python components for the fs package.


%package python3
Summary: python3 components for the fs package.
Group: Default
Requires: python3-core
Provides: pypi(fs)

%description python3
python3 components for the fs package.


%prep
%setup -q -n pyfilesystem2-2.4.11
cd %{_builddir}/pyfilesystem2-2.4.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582925000
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/fs
cp %{_builddir}/pyfilesystem2-2.4.11/LICENSE %{buildroot}/usr/share/package-licenses/fs/84803661eb311d56560c9fce4c19ce1d8db08753
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/fs/84803661eb311d56560c9fce4c19ce1d8db08753

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
